name: Unit Test

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
  merge_group:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install --immutable
      - name: Lint Project
        run: npm run lint
      - name: Test Project
        run: npm run test
